if [ -d "${HOME}/.config/bash/bashrc.d" ]; then
    for rc in ${HOME}/.config/bash/bashrc.d/* ; do
        if [ -f "$rc" ]; then
            . "$rc"
        fi
    done
fi
unset rc

if [ -d "${HOME}/.config/shell/" ]; then
    for rc in ${HOME}/.config/shell/* ; do
        if [ -f "$rc" ]; then
            . "$rc"
        fi
    done
fi
unset rc