#! /bin/zsh

if [ -n "$(echo ${HOME}/.config/zsh/zshrc.d/*(N))" ]; then
    for rc in ${HOME}/.config/zsh/zshrc.d/* ; do
        if [ -f "$rc" ]; then
            . "$rc"
        fi
    done
fi
unset rc

if [ -n "$(echo ${HOME}/.config/shell/*(N))" ]; then
    for rc in ${HOME}/.config/shell/* ; do
        if [ -f "$rc" ]; then
            . "$rc"
        fi
    done
fi
unset rc
