workspaces = false
filter_mode_shell_up_key_binding = "global"
style = "compact"
secrets_filter = true
enter_accept = true
prefers_reduced_motion = true

[sync]
records = true

[search]
filters = [ "workspace", "global", "host", "session", "directory" ]
